# Introduction to the Pandas module

## Skills

1. **Load data into Python using the pandas module.**
2. **Select columns using `[]` and rows using `DataFrame.loc[]`.**
3. **Summarize columns with basic descriptive statistics.**
4. Summarize by category using `DataFrame.groupby()`
5. Create new columns.
6. Use built-in Pandas string manipulation functions.
7. Visualize data using Seaborn and Matplotlib

## Vocabulary List

**DataFrame.** A pandas object representing structured data.

**module.** A module extends what you can do in Python, usually by adding additional functions that can be called, but can contain data, and other things as well (your instructor isn't sure on that last part, but is being safe by including it).

**Series.** A pandas object representing a single column of a DataFrame. Some functions (like `.count_values()`) return Series instead of DataFrames.

**structured data.** Data which is organized into rows and columns, like a spreadsheet. Every column of structured data must have a single data type.

## Import Modules
The code below imports the *pandas* module, allowing us to make use of more powerful data-manipulating functions and types of objects. We are binding it to a nickname of *pd*, which means that our function calls will be written as `pd.function_name()`.

In [ ]:
import pandas as pd

## Pandas DataFrame Basics

The pandas module contains many functions for loading and manipulating **structured** data.

To get started, we'll use the pandas function `read_csv()` to load in some data. Because `read_csv()` is part of the pandas library (which we imported with the nickname *pd*), we call the function with `pd.read_csv()`

The following code loads in the Netflix description dataset and stores it in a variable called `netflix`.

In [ ]:
netflix = pd.read_csv("https://raw.githubusercontent.com/Greg-Hallenbeck/class-datasets/main/datasets/netflix.csv")

The variable netflix is a special data type called a **DataFrame**, and contains everything that the "netflix.csv" file has. There are many methods associated with DataFrames, which we'll go over below.

Now that we've imported the data, what can we do with it? First, the DataFrame's `head()` function allows us to peek at a few rows of the dataset. This will be extremely useful for making sure that we haven't made any mistakes. `head()` takes a single argument, which is how many rows you want to see.

In [ ]:
netflix.head(2) #use it to see beginning entries up to "X" entry (in this case, up to the 2 index entry)

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2

Each column of a DataFrame must have a single data type. We can check what type each column is with its `dtypes` attribute. Note that `dtypes` is not a function, and so is not followed by parentheses.

The four data types you're likely to encounter with Pandas are:
* **int64** for integers.
* **float64** for floating-point (decimal) values.
* **datetime64** for dates and times (none in the Netflix data).
* **object** for anything else. This is what you'll see for strings.

In [ ]:
netflix.describe()

,release_year,runtime,seasons,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
count,5788.000000,5788.000000,2037.000000,5278.000000,5.263000e+03,5699.000000,5479.000000
mean,2016.006911,77.754492,2.169858,6.534236,2.342496e+04,22.572082,6.817850
std,7.334414,39.460795,2.641592,1.160390,8.716504e+04,68.920682,1.167537
min,1945.000000,0.000000,1.000000,1.500000,5.000000e+00,0.009442,1.000000
25%,2015.000000,45.000000,1.000000,5.800000,5.220000e+02,3.164000,6.100000
50%,2018.000000,84.000000,1.000000,6.600000,2.281000e+03,7.500000,6.900000
75%,2020.000000,105.000000,2.000000,7.400000,1.015500e+04,17.819000,7.500000
max,2022.000000,251.000000,42.000000,9.600000,2.268288e+06,1823.374000,10.000000

If instead of seeing a few rows, we want to see a particular column, we can treat our DataFrame like a list and pass in the name of a column as an index using `[]`.

In [ ]:
netflix[ ["imdb_score"] ]
# can also slice them and other list functions since its text
#adding a second set of brackets makes it more dataframey

      imdb_score
0            NaN
1            8.3
2            8.2
3            8.0
4            8.1
...          ...
5783         6.9
5784         NaN
5785         6.5
5786         6.2
5787         8.8

[5788 rows x 1 columns]

Alternatively, you can select multiple columns by passing a list of column names. This looks weird, so let's take it one step at a time. Instead of just looking at the `release_year`, let's also see the show or movie's `title`.

This means that we want both column names in a list, i.e. `["title", "release_year"]`.

We then pass that list as an index to our `netflix` DataFrame (spaces added for readability):

In [ ]:
netflix[ ["title", "release_year"] ]

                                    title  release_year
0     Five Came Back: The Reference Films          1945
1                             Taxi Driver          1976
2         Monty Python and the Holy Grail          1975
3                           Life of Brian          1979
4                            The Exorcist          1973
...                                   ...           ...
5783                            Fine Wine          2021
5784                       Edis Starlight          2021
5785                                Clash          2021
5786                       Shadow Parties          2021
5787   Mighty Little Bheem: Kite Festival          2021

[5788 rows x 2 columns]

### Selecting Rows

Instead of selecting specific columns, we can also select specific rows using the logic we learned earlier. Let's say we want to find all of the titles released after the year 2000. We can start by using the `release_year` column:

> `netflix["release_year"] > 2000`
  
This gives us a list of values which is *True* whenever the release year is after 2000 and *False* whenever it is not.

This list can then be passed to our original DataFrame, using `DataFrame.loc[]`, which takes in such a list of *True/False* values as an index.

In [ ]:
netflix["release_year"] > 2000

0       False
1       False
2       False
3       False
4       False
        ...
5783     True
5784     True
5785     True
5786     True
5787     True
Name: release_year, Length: 5788, dtype: bool

In [ ]:
netflix.loc[ netflix["release_year"] > 2000 ]

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
243,ts4,Breaking Bad,SHOW,"When Walter White, a New Mexico chemistry teac...",2008,TV-MA,48,"['drama', 'thriller', 'crime']",['US'],5.0,tt0903747,9.5,1727694.0,337.419,8.8
244,ts9,The Walking Dead,SHOW,Sheriff's deputy Rick Grimes awakens from a co...,2010,TV-MA,46,"['action', 'drama', 'scifi', 'thriller', 'horr...",['US'],11.0,tt1520211,8.2,945125.0,773.190,8.1
245,ts26091,The Staircase,SHOW,"Academy Award-winning documentary filmmaker, J...",2004,TV-MA,49,"['crime', 'documentation', 'drama']",['FR'],2.0,tt0388644,7.8,21531.0,14.185,7.7
246,ts11,Downton Abbey,SHOW,A chronicle of the lives of the aristocratic C...,2010,TV-14,58,"['drama', 'romance', 'european']",['GB'],6.0,tt1606375,8.7,197744.0,57.029,8.1
247,ts21469,Grey's Anatomy,SHOW,Follows the personal and professional lives of...,2005,TV-14,49,"['drama', 'romance']",['US'],18.0,tt0413573,7.6,293618.0,1215.393,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5783,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.9,39.0,0.966,NaN
5784,tm1108171,Edis Starlight,MOVIE,Rising star Edis's career journey with ups and...,2021,NaN,74,"['music', 'documentation']",[],NaN,NaN,NaN,NaN,1.036,8.5
5785,tm1045018,Clash,MOVIE,A man from Nigeria returns to his family in Ca...,2021,NaN,88,"['family', 'drama']","['NG', 'CA']",NaN,tt14620732,6.5,32.0,0.709,NaN
5786,tm1098060,Shadow Parties,MOVIE,A family faces destruction in a long-running c...,2021,NaN,116,"['action', 'thriller']",[],NaN,tt10168094,6.2,9.0,2.186,NaN
5787,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,0,"['family', 'comedy', 'animation']",[],1.0,tt13711094,8.8,16.0,0.979,10.0

We could also just select the movies, using `netflix["type"] == "MOVIE"`:

In [ ]:
netflix.loc[ netflix["type"] == "MOVIE" ]

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7
6,tm14873,Dirty Harry,MOVIE,When a madman dubbed 'Scorpio' terrorizes San ...,1971,R,102,"['thriller', 'crime', 'action']",['US'],NaN,tt0066999,7.7,153463.0,14.745,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5782,tm1040816,Momshies! Your Soul is Mine,MOVIE,Three women with totally different lives accid...,2021,NaN,108,['comedy'],['PH'],NaN,tt14412240,5.8,26.0,4.112,NaN
5783,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.9,39.0,0.966,NaN
5784,tm1108171,Edis Starlight,MOVIE,Rising star Edis's career journey with ups and...,2021,NaN,74,"['music', 'documentation']",[],NaN,NaN,NaN,NaN,1.036,8.5
5785,tm1045018,Clash,MOVIE,A man from Nigeria returns to his family in Ca...,2021,NaN,88,"['family', 'drama']","['NG', 'CA']",NaN,tt14620732,6.5,32.0,0.709,NaN
5786,tm1098060,Shadow Parties,MOVIE,A family faces destruction in a long-running c...,2021,NaN,116,"['action', 'thriller']",[],NaN,tt10168094,6.2,9.0,2.186,NaN

In [ ]:
netflix.loc[ netflix["imdb_score"] > 9 ]

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
243,ts4,Breaking Bad,SHOW,"When Walter White, a New Mexico chemistry teac...",2008,TV-MA,48,"['drama', 'thriller', 'crime']",['US'],5.0,tt0903747,9.5,1727694.0,337.419,8.8
259,ts3371,Avatar: The Last Airbender,SHOW,"In a war-torn world of elemental magic, a youn...",2005,TV-Y7,24,"['scifi', 'family', 'fantasy', 'animation', 'a...",['US'],3.0,tt0417299,9.3,297336.0,61.284,8.7
656,ts160526,Khawatir,SHOW,A TV show devoted to help young people to be m...,2005,TV-14,20,['reality'],[],11.0,tt3062514,9.6,3046.0,NaN,NaN
1420,ts37660,Reply 1988,SHOW,A nostalgic trip back to the late 1980s throug...,2015,TV-14,95,"['comedy', 'drama', 'family', 'romance']",['KR'],1.0,tt5182866,9.2,6557.0,15.317,8.7
2054,ts78298,My Mister,SHOW,"In a world that is less than kind, a young wom...",2018,TV-14,79,"['drama', 'family']",['KR'],1.0,tt7923710,9.2,5481.0,14.997,8.9
2920,ts265844,#ABtalks,SHOW,#ABtalks is a YouTube interview show hosted by...,2018,TV-PG,68,[],[],1.0,tt12635254,9.6,7.0,NaN,NaN
3187,ts81120,The Last Dance,SHOW,A 10-part documentary chronicling the untold s...,2020,TV-MA,50,"['documentation', 'history', 'sport']",['US'],1.0,tt8420184,9.1,108321.0,24.459,8.2
3311,ts85398,Our Planet,SHOW,Experience our planet's natural beauty and exa...,2019,TV-G,50,['documentation'],['GB'],1.0,tt9253866,9.3,41386.0,14.330,8.8
3817,ts90621,Kota Factory,SHOW,"Dedicated to Shrimati SL Loney ji, Shri Irodov...",2019,TV-MA,42,"['drama', 'comedy']",['IN'],2.0,tt9432978,9.3,66985.0,10.107,8.2
4829,ts222333,Arcane,SHOW,Amid the stark discord of twin cities Piltover...,2021,TV-14,41,"['action', 'scifi', 'drama', 'fantasy', 'anima...",['US'],1.0,tt11126994,9.1,175412.0,138.891,9.1
5041,ts296563,Who Rules The World,SHOW,A legendary wuxia romance that focuses on the ...,2022,TV-PG,44,"['drama', 'fantasy', 'romance']",['CN'],1.0,tt14950036,9.2,81.0,57.401,8.7

Or both, selecting all of the movies released after the year 2000.

You can combine logical statements with logical the *and* `&` or *or* `|` operators. When doing so, each piece should be surrounded by parentheses.

In [ ]:
netflix[ (netflix["release_year"] >= 1970) & (netflix["release_year"] < 1980) ]

As an alternative, you can use the `.query()` method. It takes in a string and lets you write your conditional statement as if the columns of the dataframe were variables. That is, you can write `release_year` instead of `netflix["release_year"]`. This is very similar to the `filter()` function in R's dplyr package.

In [ ]:
netflix.query("release_year > 2000")

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
243,ts4,Breaking Bad,SHOW,"When Walter White, a New Mexico chemistry teac...",2008,TV-MA,48,"['drama', 'thriller', 'crime']",['US'],5.0,tt0903747,9.5,1727694.0,337.419,8.8
244,ts9,The Walking Dead,SHOW,Sheriff's deputy Rick Grimes awakens from a co...,2010,TV-MA,46,"['action', 'drama', 'scifi', 'thriller', 'horr...",['US'],11.0,tt1520211,8.2,945125.0,773.190,8.1
245,ts26091,The Staircase,SHOW,"Academy Award-winning documentary filmmaker, J...",2004,TV-MA,49,"['crime', 'documentation', 'drama']",['FR'],2.0,tt0388644,7.8,21531.0,14.185,7.7
246,ts11,Downton Abbey,SHOW,A chronicle of the lives of the aristocratic C...,2010,TV-14,58,"['drama', 'romance', 'european']",['GB'],6.0,tt1606375,8.7,197744.0,57.029,8.1
247,ts21469,Grey's Anatomy,SHOW,Follows the personal and professional lives of...,2005,TV-14,49,"['drama', 'romance']",['US'],18.0,tt0413573,7.6,293618.0,1215.393,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5783,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.9,39.0,0.966,NaN
5784,tm1108171,Edis Starlight,MOVIE,Rising star Edis's career journey with ups and...,2021,NaN,74,"['music', 'documentation']",[],NaN,NaN,NaN,NaN,1.036,8.5
5785,tm1045018,Clash,MOVIE,A man from Nigeria returns to his family in Ca...,2021,NaN,88,"['family', 'drama']","['NG', 'CA']",NaN,tt14620732,6.5,32.0,0.709,NaN
5786,tm1098060,Shadow Parties,MOVIE,A family faces destruction in a long-running c...,2021,NaN,116,"['action', 'thriller']",[],NaN,tt10168094,6.2,9.0,2.186,NaN
5787,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,0,"['family', 'comedy', 'animation']",[],1.0,tt13711094,8.8,16.0,0.979,10.0

## Summary Functions

We can get summary statistics of our DataFrame using the `DataFrame.describe()` function. This will work on both the entire DataFrame, or on individual columns.

In [ ]:
netflix[ ["release_year", "imdb_score"] ].describe()

       release_year   imdb_score
count   5788.000000  5278.000000
mean    2016.006911     6.534236
std        7.334414     1.160390
min     1945.000000     1.500000
25%     2015.000000     5.800000
50%     2018.000000     6.600000
75%     2020.000000     7.400000
max     2022.000000     9.600000

If you want just one of these statistics, you can use `DataFrame.count()`, `.mean()`, `.median()`, `.min()`, `.max()` and so on. There are many more, which aren't included in the output of `.describe()`, like `DataFrame.sum()`. Here's one example:

In [ ]:
netflix["release_year"].max()

2022

Unsurprisingly, we can only use these functions on the numeric (*int64* and *float64*) columns. What is the mean title on Netflix? That question doesn't even make sense, and will raise a `TypeError` because the column is the wrong data *type*.

In [ ]:
netflix["title"].mean()

NameError: name 'netflix' is not defined

We will be doing quite a bit with *string* data, but for now, the simplest we can do is do some counting using `DataFrame.value_counts()`. Here we see that the most common rating on Netflix titles is "TV-MA" with 841 titles, followed by "R" with 575. Only 14 titles have an "NC-17" rating.

In [ ]:
netflix["age_certification"].value_counts()

TV-MA    841
R        575
TV-14    467
PG-13    440
PG       245
TV-PG    184
G        131
TV-Y7    110
TV-Y     102
TV-G      76
NC-17     14
Name: age_certification, dtype: int64

You can count the values of any column, regardless of data type. However, it only makes sense when a column has repeated values, for example the `age_certification` or `type` columns. Counting the `title` column will tell you that most movies and TV shows have unique titles. Counting the `release_year` column will tell you how many Netflix titles are from a particular year.

In [ ]:
netflix["release_year"].value_counts()

## Putting it Together

Each of these methods return a DataFrame (or, if the result is only a single column, a **Series** which is very similar), and so you can use multiple functions in a row.

**Example 1.** Let's say we want to look at recent (after the year 2000) movies, and see what their ratings are. We start by making a logical expression for recent movies:

> `(netflix["type"] == "MOVIE") & (netflix["release_year"] > 2000)`

And then select those using `DataFrame.loc[]`. To make this easier to read, I'm going to store this result in a new variable, `recentmovies`.

> `recentmovies = netflix.loc[ (netflix["type"] == "MOVIE") & (netflix["release_year"] > 2000) ]`

Now, with `recentmovies`, we can count how many there are of each rating:

> `recentmovies["age_certification"].value_counts()`

In [ ]:
recentmovies = netflix.loc[ (netflix["type"] == "MOVIE") & (netflix["release_year"] > 2000) ]

recentmovies["age_certification"].value_counts()

**Example 2.** Now, let's find what the average IMDB user rating of television shows. Let's build this up step by step. First, select only television shows. This requires the logical statement:

> `netflix["type"] == "SHOW"`

Now, select those using `DataFrame.loc[]`:

> `netflix.loc[ netflix["type"] == "SHOW" ]`

As above, we could store this new DataFrame as a new variable, like `shows`, but we don't have to. We can instead just keep adding indices and member functions, and it will work just fine. It's a bit less readable, though.

Since we want the IMDB user ratings, we'll select that column:

> `netflix.loc[ netflix["type"] == "SHOW" ]["imdb_score"]`

And then finally, using `DataFrame.mean()`:

In [ ]:
netflix.loc[ netflix["type"] == "SHOW" ]["imdb_score"].mean()